DROP TABLE IF EXISTS incomes;
DROP TABLE IF EXISTS expenses;
DROP TABLE IF EXISTS expense_categories;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS income_categories;



DROP TABLE IF EXISTS pancake;